import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../services/station_engine.dart';

class SettingsScreen extends StatelessWidget {
  const SettingsScreen({super.key});

  Future<void> _confirmReset(BuildContext context) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Reset listening history?'),
        content: const Text(
          'This wipes every station\'s queue and history (including custom '
          'stations) and re-warms the defaults from scratch. New songs will '
          'be generated by the LLM and re-picked on YouTube. This cannot be '
          'undone.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(false),
            child: const Text('Cancel'),
          ),
          FilledButton(
            style: FilledButton.styleFrom(backgroundColor: Colors.red),
            onPressed: () => Navigator.of(ctx).pop(true),
            child: const Text('Reset'),
          ),
        ],
      ),
    );
    if (confirmed != true || !context.mounted) return;
    final engine = context.read<StationEngine>();
    final messenger = ScaffoldMessenger.of(context);
    await engine.resetAll();
    messenger.showSnackBar(
      const SnackBar(
        duration: Duration(seconds: 2),
        content: Text('Listening history cleared. Re-warming stations…'),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Settings')),
      body: ListView(
        children: [
          const Padding(
            padding: EdgeInsets.fromLTRB(16, 16, 16, 8),
            child: Text(
              'Listening history',
              style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
            ),
          ),
          ListTile(
            leading: const Icon(Icons.delete_forever, color: Colors.red),
            title: const Text('Reset listening history'),
            subtitle: const Text(
              'Wipe all stations & queues and force fresh LLM generation.',
            ),
            onTap: () => _confirmReset(context),
          ),
        ],
      ),
    );
  }
}
